set -g default-terminal "screen-256color"

# Prefix
set -g prefix C-a

# Sort by name
bind s choose-tree -sZ -O name

# Index replacement
set -g base-index 1
setw -g pane-base-index 1

# Keybindings overrides
unbind %
bind | split-window -h

# unbind '"'
# bind \ split window -v

unbind r
bind r source-file ~/.tmux.conf


bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-ressurect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'
# set -g @plugin 'catppuccin/tmux'
set -g @plugin "arcticicestudio/nord-tmux"
# set -g @catppuccin_flavour 'ayu' # latte or frappe, macchiato, mocha

# Sessions
set -g @resurect-capture-pane-contents 'on'
set -g @continuum-resotre 'on'

# Powerline
set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
set-hook -g session-created 'run-shell "~/path/to/tmux-powerline/powerline.sh init"' # prettifies the window-status segments

# Required
run '~/.tmux/plugins/tpm/tpm'
