"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_green)\
$os\
[](bg:color_surface fg:color_green)\
$directory\
[](fg:color_surface)\
($git_status [](fg:color_cyan))\
($c$rust$golang$nodejs$php$java$kotlin$haskell$python[ ](fg:color_green))\
$character"""

palette = 'nordic'

[palettes.mocha]
color_base = '#1e1e2e'
color_surface = '#313244'
color_overlay = '#45475a'
color_muted = '#585b70'
color_subtle = '#a6adc8'
color_text = '#cdd6f4'
color_pink = '#f5c2e7'
color_yellow = '#f9e2af'
color_orange = '#fab387'
color_green = '#a6e3a1'
color_cyan = '#89dceb'
color_blue = '#b2beff'
color_docker = '#1d90ed'
color_hl_low = '#313244'
[palettes.dragon]
color_base = '#12120f'
color_surface = '#181616'
color_overlay = '#282727'
color_muted = '#383835'
color_subtle = '#625e5a'
color_text = '#c5c9c5'
color_pink = '#a292a3'
color_yellow = '#ccc28f'
color_orange = '#b6927b'
color_green = '#717c71'
color_cyan = '#8ea4a2'
color_blue = '#8992a7'
color_docker = '#1d90ed'
color_hl_low = '#181616'
[palettes.rosepine]
color_base = '#191724'
color_surface = '#1f1d2e'
color_overlay = '#26233a'
color_muted = '#6e6a86'
color_subtle = '#908caa'
color_text = '#e0def4'
color_pink = '#eb6f92'
color_yellow = '#f6c177'
color_orange = '#ebbcba'
color_green = '#31748f'
color_cyan = '#9ccfd8'
color_blue = '#c4a7e7'
color_docker = '#1d90ed'
color_hl_low = '#21202e'
[palettes.nordic]
color_base = '#232831'
color_surface = '#2e3440'
color_overlay = '#39404f'
color_muted = '#z444c5e'
color_subtle = '#5a657d'
color_text = '#c7cdd9'
color_pink = '#bf88bc'
color_yellow = '#ebcb8b'
color_orange = '#c9826b'
color_green = '#a3be8c'
color_cyan = '#88c0d0'
color_blue = '#81a1c1'
color_docker = '#1d90ed'
color_hl_low = '#232831'


[os]
disabled = false
style = "bg:color_green fg:color_base"
format = '[$symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = " 󰀵 "
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_yellow fg:color_text"
style_root = "bg:color_yellow fg:color_text"
format = '[ $user ]($style)'

[directory]
style = "fg:color_text bg:color_surface"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "
"ArrivedAliens" = "󱃅 "
".dotfiles" = " "

[git_branch]
symbol = ""
style = "fg:color_text"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_text"
format = '[[($all_status$ahead_behind)](fg:color_subtle)]($style)'

[nodejs]
symbol = ""
style = "fg:color_text"
format = '[ $symbol](fg:#68a063)[( $version)]($style)'

[c]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_text bg:color_green)]($style)'

[rust]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_text bg:color_green)]($style)'

[golang]
symbol = ""
style = "fg:color_text"
format = '[ $symbol](fg:#00ADD8)[]( $version)]($style)'

[php]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_text bg:color_green)]($style)'

[java]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_text bg:color_green)]($style)'

[kotlin]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_text bg:color_green)]($style)'

[haskell]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_text bg:color_green)]($style)'

[python]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_text bg:color_green)]($style)'

[docker_context]
symbol = ""
style =  "fg:color_text"
format = '[ $symbol](fg:color_docker)[( $context)]($style)'

[conda]
style = "bg:color_muted"
format = '[[ $symbol( $environment) ](fg:color_text bg:color_muted)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_base"
format = '[[  $time ](fg:color_text bg:color_base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_cyan)'
error_symbol = '[](bold fg:color_pink)'
vimcmd_symbol = '[](bold fg:color_cyan)'
vimcmd_replace_one_symbol = '[](bold fg:color_blue)'
vimcmd_replace_symbol = '[](bold fg:color_blue)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
