set_theme() {
    case $1 in
        rosepine)
            white=$rosepine_text
            gray=$rosepine_surface
            dark_gray=$rosepine_base
            light_purple=$rosepine_rose
            dark_purple=$rosepine_base
            cyan=$rosepine_foam
            green=$rosepine_love
            light_green=$rosepine_pine
            orange=$rosepine_gold
            red=$rosepine_love
            pink=$rosepine_rose
            yellow=$rosepine_gold
            blue=$rosepine_blue
            ;;
        wave)
            white=$wave_text
            gray=$wave_surface
            dark_gray=$wave_base
            light_purple=$wave_pink
            dark_purple=$wave_base
            cyan=$wave_cyan
            green=$wave_pink
            light_green=$wave_green
            orange=$wave_yellow
            red=$wave_red
            pink=$wave_pink
            yellow=$wave_yellow
            blue=$wave_blue
            ;;
    esac
}
